
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jun 24 2026 12:01:36 IST (Jun 24 2026 06:31:36 UTC)

// Verification Directory fv/booth_multiplier 

module booth_multiplier(clk, load, reset, M, Q, P);
  input clk, load, reset;
  input [3:0] M, Q;
  output [7:0] P;
  wire clk, load, reset;
  wire [3:0] M, Q;
  wire [7:0] P;
  wire [2:0] Count;
  wire [3:0] M_temp;
  wire Q_minus_one, n_1, n_3, n_4, n_5, n_6, n_8, n_9;
  wire n_10, n_14, n_20, n_21, n_22, n_26, n_27, n_28;
  wire n_30, n_34, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_44, n_48, n_50, n_51, n_52, n_53, n_56;
  wire n_58, n_59, n_60, n_67, n_68, n_69, n_70, n_71;
  wire n_75, n_76, n_77, n_79, n_80, n_85, n_86, n_87;
  wire n_90, n_91, n_92, n_93, n_96, n_97, n_98, n_124;
  wire n_192, n_193, n_194, n_199, n_200, n_201, n_203, n_209;
  wire n_214, n_227, n_229, n_231, n_232, n_234, n_235, n_236;
  wire n_237, n_238, n_239, n_240, n_241, n_242, n_243, n_245;
  wire n_246, n_247, n_251, n_255, n_256, n_257, n_261, n_262;
  wire n_275, n_276, n_277, n_278, n_281, n_296, n_297, n_298;
  wire n_303, n_307, n_308, n_309, n_311, n_313, n_314, n_316;
  wire n_317, n_318, n_322, n_323, n_326, n_327, n_328, n_329;
  wire n_330, n_331, n_332, n_333, n_334, n_335, n_336, n_337;
  wire n_338, n_348, n_350, n_352, n_353, n_355, n_356, n_357;
  wire n_358, n_359, n_373, n_388, n_389, n_390, n_391, n_392;
  wire n_393, n_394, n_403, n_404, n_405, n_407, n_446, n_448;
  assign P[6] = P[7];
  DFFQX4 \A_reg[2] (.CK (clk), .D (n_392), .Q (P[7]));
  DFFHQX1 \A_reg[1] (.CK (clk), .D (n_326), .Q (P[5]));
  DFFHQX1 \A_reg[0] (.CK (clk), .D (n_246), .Q (P[4]));
  OAI21X1 g10381__1617(.A0 (Q_minus_one), .A1 (n_87), .B0 (n_96), .Y
       (n_98));
  AOI21XL g10386__2802(.A0 (n_96), .A1 (n_80), .B0 (n_358), .Y (n_97));
  DFFHQX1 \P_reg[1] (.CK (clk), .D (n_90), .Q (P[1]));
  DFFHQX1 \P_reg[2] (.CK (clk), .D (n_85), .Q (P[2]));
  DFFHQX1 \P_reg[3] (.CK (clk), .D (n_86), .Q (P[3]));
  DFFHQX1 \Count_reg[1] (.CK (clk), .D (n_79), .Q (Count[1]));
  AOI21X1 g10385__5122(.A0 (n_92), .A1 (n_68), .B0 (n_124), .Y (n_93));
  DFFHQX1 \P_reg[0] (.CK (clk), .D (n_356), .Q (P[0]));
  AOI21XL g10397__8246(.A0 (n_70), .A1 (n_69), .B0 (n_71), .Y (n_91));
  OAI21X1 g10379__7098(.A0 (n_393), .A1 (n_338), .B0 (n_194), .Y
       (n_90));
  AOI21XL g10398__1881(.A0 (n_76), .A1 (n_75), .B0 (n_77), .Y (n_87));
  OAI21X1 g10383__5115(.A0 (n_60), .A1 (n_338), .B0 (n_278), .Y (n_86));
  OAI21X1 g10382__7482(.A0 (n_352), .A1 (n_338), .B0 (n_311), .Y
       (n_85));
  MDFFHQX2 \Count_reg[0] (.CK (clk), .D0 (n_337), .D1 (n_262), .S0
       (Count[0]), .Q (Count[0]));
  DFFQX1 Q_minus_one_reg(.CK (clk), .D (n_275), .Q (Q_minus_one));
  NAND2XL g10403__9315(.A (n_235), .B (n_67), .Y (n_80));
  OAI21X1 g10384__9945(.A0 (n_6), .A1 (n_199), .B0 (n_318), .Y (n_79));
  NOR2XL g10409__2346(.A (n_76), .B (n_75), .Y (n_77));
  NOR2XL g10404__7410(.A (n_70), .B (n_69), .Y (n_71));
  NAND2XL g10405__6417(.A (Q_minus_one), .B (n_59), .Y (n_68));
  OAI21XL g10422__5477(.A0 (n_58), .A1 (n_56), .B0 (n_48), .Y (n_67));
  AOI22XL g10421__4319(.A0 (n_51), .A1 (n_359), .B0 (n_281), .B1
       (n_34), .Y (n_60));
  OAI21XL g10420__8428(.A0 (n_58), .A1 (n_39), .B0 (n_40), .Y (n_59));
  OAI21X1 g10424__6783(.A0 (n_22), .A1 (n_56), .B0 (n_448), .Y (n_75));
  OAI2BB1X1 g10423__3680(.A0N (M_temp[2]), .A1N (n_203), .B0 (n_38), .Y
       (n_69));
  AOI21XL g10435__2802(.A0 (n_36), .A1 (n_50), .B0 (n_37), .Y (n_53));
  OAI21X1 g10434__1705(.A0 (n_51), .A1 (n_50), .B0 (n_41), .Y (n_52));
  NAND2XL g10433__7098(.A (n_58), .B (n_56), .Y (n_48));
  DFFHQX1 \M_temp_reg[3] (.CK (clk), .D (n_30), .Q (M_temp[3]));
  DFFHQX2 \M_temp_reg[2] (.CK (clk), .D (n_26), .Q (M_temp[2]));
  DFFHQX2 \M_temp_reg[0] (.CK (clk), .D (n_28), .Q (M_temp[0]));
  DFFHQX2 \M_temp_reg[1] (.CK (clk), .D (n_27), .Q (M_temp[1]));
  NOR2BX1 g10415__5115(.AN (n_348), .B (n_229), .Y (n_44));
  INVXL g10413(.A (n_358), .Y (n_42));
  DFFHQX2 \Count_reg[2] (.CK (clk), .D (n_407), .Q (Count[2]));
  NAND2XL g10436__4733(.A (n_51), .B (n_50), .Y (n_41));
  NAND2XL g10432__6161(.A (n_39), .B (n_58), .Y (n_40));
  OAI21XL g10431__9315(.A0 (M_temp[2]), .A1 (n_203), .B0 (n_39), .Y
       (n_38));
  NOR2XL g10438__9945(.A (n_36), .B (n_50), .Y (n_37));
  NAND2XL g10437__2883(.A (M_temp[0]), .B (n_359), .Y (n_34));
  AOI2BB1X1 g10439__2346(.A0N (n_51), .A1N (n_20), .B0 (n_21), .Y
       (n_56));
  OAI21X1 g10442__6417(.A0 (n_4), .A1 (n_199), .B0 (n_333), .Y (n_30));
  OAI21X1 g10441__5477(.A0 (n_1), .A1 (n_199), .B0 (n_331), .Y (n_28));
  OAI21X1 g10440__2398(.A0 (n_5), .A1 (n_199), .B0 (n_334), .Y (n_27));
  OAI21X1 g10443__5107(.A0 (n_3), .A1 (n_199), .B0 (n_336), .Y (n_26));
  INVXL g10449(.A (n_76), .Y (n_70));
  OAI22X1 g10444__4319(.A0 (n_36), .A1 (n_8), .B0 (n_214), .B1 (n_10),
       .Y (n_39));
  NOR2BX1 g10453__5526(.AN (n_448), .B (n_22), .Y (n_58));
  OR2X1 g10452__6783(.A (n_21), .B (n_20), .Y (n_50));
  AOI21XL g10450__5122(.A0 (Count[1]), .A1 (Count[0]), .B0 (n_404), .Y
       (n_14));
  MXI2XL g10454__6131(.A (n_200), .B (n_201), .S0 (M_temp[3]), .Y
       (n_76));
  NOR2XL g10469__5115(.A (n_201), .B (n_9), .Y (n_22));
  NAND2XL g10468__7482(.A (n_203), .B (n_235), .Y (n_92));
  NOR2XL g10467__4733(.A (P[5]), .B (n_10), .Y (n_20));
  NOR2XL g10465__9315(.A (M_temp[1]), .B (n_214), .Y (n_21));
  NOR2XL g10456__2883(.A (P[5]), .B (M_temp[1]), .Y (n_8));
  NAND2XL g10458__7410(.A (n_203), .B (Q_minus_one), .Y (n_96));
  NAND2XL g10460__5477(.A (P[4]), .B (M_temp[0]), .Y (n_36));
  NOR2BX1 g10461__2398(.AN (M_temp[0]), .B (P[4]), .Y (n_51));
  INVXL g10481(.A (Count[1]), .Y (n_6));
  CLKINVX1 g10480(.A (M[1]), .Y (n_5));
  CLKINVX1 g10478(.A (M[3]), .Y (n_4));
  CLKINVX1 g10477(.A (M[2]), .Y (n_3));
  CLKINVX1 g10479(.A (M[0]), .Y (n_1));
  CLKINVX1 g10484(.A (M_temp[2]), .Y (n_9));
  CLKINVX1 g10483(.A (M_temp[1]), .Y (n_10));
  CLKINVX2 fopt10502(.A (n_236), .Y (n_124));
  AOI31X1 g123(.A0 (load), .A1 (Q[1]), .A2 (n_303), .B0 (n_193), .Y
       (n_194));
  NOR3X2 g124(.A (n_192), .B (load), .C (reset), .Y (n_193));
  NAND2BX1 g126(.AN (n_255), .B (n_348), .Y (n_192));
  NAND2X6 g131(.A (load), .B (n_296), .Y (n_199));
  INVX1 fopt10554(.A (n_200), .Y (n_201));
  CLKINVX2 fopt10561(.A (n_209), .Y (n_203));
  CLKBUFX2 fopt10562(.A (n_200), .Y (n_209));
  CLKINVX1 fopt10563(.A (P[7]), .Y (n_200));
  NAND3XL g529(.A (n_232), .B (n_242), .C (n_245), .Y (n_246));
  NAND2XL g535(.A (n_227), .B (n_231), .Y (n_232));
  NOR2BX1 g548(.AN (n_281), .B (reset), .Y (n_227));
  CLKINVX1 g537(.A (n_446), .Y (n_231));
  CLKINVX3 g542(.A (n_255), .Y (n_229));
  NAND2XL g530(.A (n_240), .B (n_241), .Y (n_242));
  AOI222XL g531(.A0 (n_237), .A1 (n_358), .B0 (Q_minus_one), .B1
       (n_238), .C0 (n_52), .C1 (n_239), .Y (n_240));
  NAND3X1 g534(.A (n_234), .B (n_235), .C (n_236), .Y (n_237));
  CLKINVX1 g551(.A (n_214), .Y (n_234));
  CLKINVX1 g552(.A (P[5]), .Y (n_214));
  CLKINVX1 g549(.A (Q_minus_one), .Y (n_235));
  AND2X1 g536(.A (n_355), .B (n_255), .Y (n_236));
  NAND2XL g541(.A (n_234), .B (Q_minus_one), .Y (n_238));
  AND2XL g532(.A (n_238), .B (n_237), .Y (n_239));
  NOR2X4 g545(.A (load), .B (reset), .Y (n_241));
  NAND2X1 g533(.A (n_243), .B (n_388), .Y (n_245));
  NOR2XL g547(.A (n_235), .B (n_53), .Y (n_243));
  CLKINVX1 g544(.A (n_241), .Y (n_247));
  CLKINVX2 fopt(.A (load), .Y (n_251));
  NAND2BXL g10570(.AN (n_256), .B (n_394), .Y (n_257));
  BUFX2 g10571(.A (n_255), .Y (n_256));
  NAND2X2 g133(.A (n_403), .B (n_404), .Y (n_255));
  NOR2X4 g10572(.A (reset), .B (n_261), .Y (n_262));
  CLKINVX6 fopt139(.A (load), .Y (n_261));
  OAI32X1 g48(.A0 (n_235), .A1 (reset), .A2 (n_446), .B0 (n_358), .B1
       (n_247), .Y (n_275));
  AOI21X1 g188(.A0 (n_262), .A1 (Q[3]), .B0 (n_277), .Y (n_278));
  NOR3X1 g189(.A (n_276), .B (reset), .C (load), .Y (n_277));
  NAND2BXL g191(.AN (n_256), .B (n_353), .Y (n_276));
  DLY2X1 fopt10573(.A (P[4]), .Y (n_281));
  CLKINVX8 fopt10580(.A (reset), .Y (n_296));
  CLKINVX3 fopt10581(.A (reset), .Y (n_297));
  CLKINVX2 fopt10582(.A (reset), .Y (n_298));
  CLKINVX6 fopt10584(.A (reset), .Y (n_303));
  OAI21X1 g154(.A0 (n_307), .A1 (n_309), .B0 (n_303), .Y (n_311));
  NOR2X1 g156(.A (n_257), .B (load), .Y (n_307));
  NOR2X1 g155(.A (n_308), .B (n_251), .Y (n_309));
  INVX3 g157(.A (Q[2]), .Y (n_308));
  NAND2X1 g18(.A (n_251), .B (n_313), .Y (n_314));
  NOR2X2 g19(.A (n_256), .B (reset), .Y (n_313));
  NAND2X1 g24(.A (n_303), .B (n_317), .Y (n_318));
  NOR2BX2 g25(.AN (n_316), .B (load), .Y (n_317));
  NOR2XL g26(.A (n_14), .B (n_229), .Y (n_316));
  NAND4XL g117(.A (n_322), .B (n_323), .C (n_329), .D (n_328), .Y
       (n_326));
  NAND3X1 g119(.A (n_234), .B (n_229), .C (n_297), .Y (n_322));
  NAND3X1 g118(.A (n_234), .B (load), .C (n_298), .Y (n_323));
  NAND2X1 g10588(.A (n_97), .B (n_327), .Y (n_328));
  NOR2X8 g10589(.A (load), .B (reset), .Y (n_327));
  NAND2X1 g10590(.A (n_93), .B (n_327), .Y (n_329));
  NAND3XL g10372__10591(.A (n_42), .B (n_98), .C (n_327), .Y (n_330));
  NAND2X1 g10448__10592(.A (M_temp[0]), .B (n_327), .Y (n_331));
  NAND2X1 g10447__10593(.A (M_temp[3]), .B (n_332), .Y (n_333));
  NOR2X8 g546_dup(.A (load), .B (reset), .Y (n_332));
  NAND2X1 g10446__10594(.A (M_temp[1]), .B (n_332), .Y (n_334));
  AOI22X1 g10399__10595(.A0 (n_332), .A1 (n_44), .B0 (Q[0]), .B1
       (n_262), .Y (n_335));
  NAND2X1 g10445__10596(.A (M_temp[2]), .B (n_332), .Y (n_336));
  CLKINVX2 g35(.A (n_337), .Y (n_338));
  NOR3X6 g36(.A (n_229), .B (load), .C (reset), .Y (n_337));
  INVX1 fopt1(.A (n_350), .Y (n_348));
  INVXL fopt10603(.A (P[1]), .Y (n_350));
  INVXL fopt10604(.A (n_353), .Y (n_352));
  CLKBUFX2 fopt10605(.A (P[3]), .Y (n_353));
  OAI21X1 g10387__10606(.A0 (n_355), .A1 (n_314), .B0 (n_335), .Y
       (n_356));
  INVXL g10607(.A (P[0]), .Y (n_355));
  NAND2X1 g10417__10608(.A (n_357), .B (n_255), .Y (n_358));
  BUFX2 g10609(.A (P[0]), .Y (n_357));
  AOI22XL g10451__10610(.A0 (n_355), .A1 (n_235), .B0 (n_357), .B1
       (Q_minus_one), .Y (n_359));
  CLKINVX1 g39(.A (n_403), .Y (n_373));
  NOR3X8 g10633(.A (n_124), .B (reset), .C (load), .Y (n_388));
  NAND2XL g10364__10634(.A (n_330), .B (n_391), .Y (n_392));
  AOI21X1 g10368__10635(.A0 (n_388), .A1 (n_389), .B0 (n_390), .Y
       (n_391));
  OAI21XL g10380__10636(.A0 (n_235), .A1 (n_91), .B0 (n_92), .Y
       (n_389));
  NOR3BX2 g10637(.AN (n_203), .B (reset), .C (n_446), .Y (n_390));
  INVXL fopt10638(.A (n_394), .Y (n_393));
  CLKBUFX2 fopt10639(.A (P[2]), .Y (n_394));
  CLKINVX2 g10642(.A (Count[2]), .Y (n_403));
  OAI211X1 g10643(.A0 (n_403), .A1 (n_404), .B0 (n_303), .C0 (n_405),
       .Y (n_407));
  NOR2X2 g10644(.A (Count[0]), .B (Count[1]), .Y (n_404));
  NAND2X4 g10645(.A (n_373), .B (load), .Y (n_405));
  NOR2X4 g10419__10514_dup10674(.A (n_229), .B (load), .Y (n_446));
  NAND2BX1 g2(.AN (n_200), .B (n_9), .Y (n_448));
endmodule

