/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cadence)
#  Generated on:      Wed Jun 24 13:47:27 2026
#  Design:            booth_multiplier
#  Command:           saveNetlist ../day20/booth/booth_physical_netlist.v
###############################################################
*/
module booth_multiplier (
	clk, 
	load, 
	reset, 
	M, 
	Q, 
	P);
   input clk;
   input load;
   input reset;
   input [3:0] M;
   input [3:0] Q;
   output [7:0] P;

   // Internal wires
   wire FE_DBTN1_load;
   wire FE_DBTN0_reset;
   wire [2:0] Count;
   wire [3:0] M_temp;
   wire Q_minus_one;
   wire n_1;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_14;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_30;
   wire n_34;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_44;
   wire n_48;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_56;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_79;
   wire n_80;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_124;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_199;
   wire n_200;
   wire n_214;
   wire n_227;
   wire n_229;
   wire n_231;
   wire n_232;
   wire n_235;
   wire n_236;
   wire n_237;
   wire n_238;
   wire n_239;
   wire n_240;
   wire n_241;
   wire n_242;
   wire n_243;
   wire n_245;
   wire n_246;
   wire n_247;
   wire n_255;
   wire n_257;
   wire n_262;
   wire n_275;
   wire n_276;
   wire n_277;
   wire n_278;
   wire n_307;
   wire n_308;
   wire n_309;
   wire n_311;
   wire n_313;
   wire n_314;
   wire n_316;
   wire n_317;
   wire n_318;
   wire n_322;
   wire n_323;
   wire n_326;
   wire n_327;
   wire n_328;
   wire n_329;
   wire n_330;
   wire n_331;
   wire n_332;
   wire n_333;
   wire n_334;
   wire n_335;
   wire n_336;
   wire n_337;
   wire n_338;
   wire n_352;
   wire n_355;
   wire n_356;
   wire n_358;
   wire n_359;
   wire n_388;
   wire n_389;
   wire n_390;
   wire n_391;
   wire n_392;
   wire n_393;
   wire n_403;
   wire n_404;
   wire n_405;
   wire n_407;
   wire n_446;
   wire n_448;

   assign P[6] = P[7] ;

   CLKINVX6 FE_DBTC1_load (.A(load),
	.Y(FE_DBTN1_load));
   CLKINVX6 FE_DBTC0_reset (.A(reset),
	.Y(FE_DBTN0_reset));
   DFFQX4 \A_reg[2]  (.CK(clk),
	.D(n_392),
	.Q(P[7]));
   DFFHQX1 \A_reg[1]  (.CK(clk),
	.D(n_326),
	.Q(P[5]));
   DFFHQX1 \A_reg[0]  (.CK(clk),
	.D(n_246),
	.Q(P[4]));
   OAI21X1 g10381__1617 (.A0(Q_minus_one),
	.A1(n_87),
	.B0(n_96),
	.Y(n_98));
   AOI21XL g10386__2802 (.A0(n_96),
	.A1(n_80),
	.B0(n_358),
	.Y(n_97));
   DFFHQX1 \P_reg[1]  (.CK(clk),
	.D(n_90),
	.Q(P[1]));
   DFFHQX1 \P_reg[2]  (.CK(clk),
	.D(n_85),
	.Q(P[2]));
   DFFHQX1 \P_reg[3]  (.CK(clk),
	.D(n_86),
	.Q(P[3]));
   DFFHQX1 \Count_reg[1]  (.CK(clk),
	.D(n_79),
	.Q(Count[1]));
   AOI21X1 g10385__5122 (.A0(n_92),
	.A1(n_68),
	.B0(n_124),
	.Y(n_93));
   DFFHQX1 \P_reg[0]  (.CK(clk),
	.D(n_356),
	.Q(P[0]));
   AOI21XL g10397__8246 (.A0(n_70),
	.A1(n_69),
	.B0(n_71),
	.Y(n_91));
   OAI21X1 g10379__7098 (.A0(n_393),
	.A1(n_338),
	.B0(n_194),
	.Y(n_90));
   AOI21XL g10398__1881 (.A0(n_76),
	.A1(n_75),
	.B0(n_77),
	.Y(n_87));
   OAI21X1 g10383__5115 (.A0(n_60),
	.A1(n_338),
	.B0(n_278),
	.Y(n_86));
   OAI21X1 g10382__7482 (.A0(n_352),
	.A1(n_338),
	.B0(n_311),
	.Y(n_85));
   MDFFHQX2 \Count_reg[0]  (.CK(clk),
	.D0(n_337),
	.D1(n_262),
	.Q(Count[0]),
	.S0(Count[0]));
   DFFQX1 Q_minus_one_reg (.CK(clk),
	.D(n_275),
	.Q(Q_minus_one));
   NAND2XL g10403__9315 (.A(n_235),
	.B(n_67),
	.Y(n_80));
   OAI21X1 g10384__9945 (.A0(n_6),
	.A1(n_199),
	.B0(n_318),
	.Y(n_79));
   NOR2XL g10409__2346 (.A(n_76),
	.B(n_75),
	.Y(n_77));
   NOR2XL g10404__7410 (.A(n_70),
	.B(n_69),
	.Y(n_71));
   NAND2XL g10405__6417 (.A(Q_minus_one),
	.B(n_59),
	.Y(n_68));
   OAI21XL g10422__5477 (.A0(n_58),
	.A1(n_56),
	.B0(n_48),
	.Y(n_67));
   AOI22XL g10421__4319 (.A0(n_51),
	.A1(n_359),
	.B0(P[4]),
	.B1(n_34),
	.Y(n_60));
   OAI21XL g10420__8428 (.A0(n_58),
	.A1(n_39),
	.B0(n_40),
	.Y(n_59));
   OAI21X1 g10424__6783 (.A0(n_22),
	.A1(n_56),
	.B0(n_448),
	.Y(n_75));
   OAI2BB1X1 g10423__3680 (.A0N(M_temp[2]),
	.A1N(P[6]),
	.B0(n_38),
	.Y(n_69));
   AOI21XL g10435__2802 (.A0(n_36),
	.A1(n_50),
	.B0(n_37),
	.Y(n_53));
   OAI21X1 g10434__1705 (.A0(n_51),
	.A1(n_50),
	.B0(n_41),
	.Y(n_52));
   NAND2XL g10433__7098 (.A(n_58),
	.B(n_56),
	.Y(n_48));
   DFFHQX1 \M_temp_reg[3]  (.CK(clk),
	.D(n_30),
	.Q(M_temp[3]));
   DFFHQX2 \M_temp_reg[2]  (.CK(clk),
	.D(n_26),
	.Q(M_temp[2]));
   DFFHQX2 \M_temp_reg[0]  (.CK(clk),
	.D(n_28),
	.Q(M_temp[0]));
   DFFHQX2 \M_temp_reg[1]  (.CK(clk),
	.D(n_27),
	.Q(M_temp[1]));
   NOR2BX1 g10415__5115 (.AN(P[1]),
	.B(n_229),
	.Y(n_44));
   INVXL g10413 (.A(n_358),
	.Y(n_42));
   DFFHQX2 \Count_reg[2]  (.CK(clk),
	.D(n_407),
	.Q(Count[2]));
   NAND2XL g10436__4733 (.A(n_51),
	.B(n_50),
	.Y(n_41));
   NAND2XL g10432__6161 (.A(n_39),
	.B(n_58),
	.Y(n_40));
   OAI21XL g10431__9315 (.A0(M_temp[2]),
	.A1(P[6]),
	.B0(n_39),
	.Y(n_38));
   NOR2XL g10438__9945 (.A(n_36),
	.B(n_50),
	.Y(n_37));
   NAND2XL g10437__2883 (.A(M_temp[0]),
	.B(n_359),
	.Y(n_34));
   AOI2BB1X1 g10439__2346 (.A0N(n_51),
	.A1N(n_20),
	.B0(n_21),
	.Y(n_56));
   OAI21X1 g10442__6417 (.A0(n_4),
	.A1(n_199),
	.B0(n_333),
	.Y(n_30));
   OAI21X1 g10441__5477 (.A0(n_1),
	.A1(n_199),
	.B0(n_331),
	.Y(n_28));
   OAI21X1 g10440__2398 (.A0(n_5),
	.A1(n_199),
	.B0(n_334),
	.Y(n_27));
   OAI21X1 g10443__5107 (.A0(n_3),
	.A1(n_199),
	.B0(n_336),
	.Y(n_26));
   INVXL g10449 (.A(n_76),
	.Y(n_70));
   OAI22X1 g10444__4319 (.A0(n_36),
	.A1(n_8),
	.B0(n_214),
	.B1(n_10),
	.Y(n_39));
   NOR2BX1 g10453__5526 (.AN(n_448),
	.B(n_22),
	.Y(n_58));
   OR2X1 g10452__6783 (.A(n_21),
	.B(n_20),
	.Y(n_50));
   AOI21XL g10450__5122 (.A0(Count[1]),
	.A1(Count[0]),
	.B0(n_404),
	.Y(n_14));
   MXI2XL g10454__6131 (.A(n_200),
	.B(P[6]),
	.S0(M_temp[3]),
	.Y(n_76));
   NOR2XL g10469__5115 (.A(P[6]),
	.B(n_9),
	.Y(n_22));
   NAND2XL g10468__7482 (.A(P[6]),
	.B(n_235),
	.Y(n_92));
   NOR2XL g10467__4733 (.A(P[5]),
	.B(n_10),
	.Y(n_20));
   NOR2XL g10465__9315 (.A(M_temp[1]),
	.B(n_214),
	.Y(n_21));
   NOR2XL g10456__2883 (.A(P[5]),
	.B(M_temp[1]),
	.Y(n_8));
   NAND2XL g10458__7410 (.A(P[6]),
	.B(Q_minus_one),
	.Y(n_96));
   NAND2XL g10460__5477 (.A(P[4]),
	.B(M_temp[0]),
	.Y(n_36));
   NOR2BX1 g10461__2398 (.AN(M_temp[0]),
	.B(P[4]),
	.Y(n_51));
   INVXL g10481 (.A(Count[1]),
	.Y(n_6));
   CLKINVX1 g10480 (.A(M[1]),
	.Y(n_5));
   CLKINVX1 g10478 (.A(M[3]),
	.Y(n_4));
   CLKINVX1 g10477 (.A(M[2]),
	.Y(n_3));
   CLKINVX1 g10479 (.A(M[0]),
	.Y(n_1));
   CLKINVX1 g10484 (.A(M_temp[2]),
	.Y(n_9));
   CLKINVX1 g10483 (.A(M_temp[1]),
	.Y(n_10));
   CLKINVX2 fopt10502 (.A(n_236),
	.Y(n_124));
   AOI31X1 g123 (.A0(load),
	.A1(Q[1]),
	.A2(FE_DBTN0_reset),
	.B0(n_193),
	.Y(n_194));
   NOR3X2 g124 (.A(n_192),
	.B(load),
	.C(reset),
	.Y(n_193));
   NAND2BX1 g126 (.AN(n_255),
	.B(P[1]),
	.Y(n_192));
   NAND2X6 g131 (.A(load),
	.B(FE_DBTN0_reset),
	.Y(n_199));
   CLKINVX1 fopt10563 (.A(P[7]),
	.Y(n_200));
   NAND3XL g529 (.A(n_232),
	.B(n_242),
	.C(n_245),
	.Y(n_246));
   NAND2XL g535 (.A(n_227),
	.B(n_231),
	.Y(n_232));
   NOR2BX1 g548 (.AN(P[4]),
	.B(reset),
	.Y(n_227));
   CLKINVX1 g537 (.A(n_446),
	.Y(n_231));
   CLKINVX3 g542 (.A(n_255),
	.Y(n_229));
   NAND2XL g530 (.A(n_240),
	.B(n_241),
	.Y(n_242));
   AOI222XL g531 (.A0(n_237),
	.A1(n_358),
	.B0(Q_minus_one),
	.B1(n_238),
	.C0(n_52),
	.C1(n_239),
	.Y(n_240));
   NAND3X1 g534 (.A(P[5]),
	.B(n_235),
	.C(n_236),
	.Y(n_237));
   CLKINVX1 g552 (.A(P[5]),
	.Y(n_214));
   CLKINVX1 g549 (.A(Q_minus_one),
	.Y(n_235));
   AND2X1 g536 (.A(n_355),
	.B(n_255),
	.Y(n_236));
   NAND2XL g541 (.A(P[5]),
	.B(Q_minus_one),
	.Y(n_238));
   AND2XL g532 (.A(n_238),
	.B(n_237),
	.Y(n_239));
   NOR2X4 g545 (.A(load),
	.B(reset),
	.Y(n_241));
   NAND2X1 g533 (.A(n_243),
	.B(n_388),
	.Y(n_245));
   NOR2XL g547 (.A(n_235),
	.B(n_53),
	.Y(n_243));
   CLKINVX1 g544 (.A(n_241),
	.Y(n_247));
   NAND2BXL g10570 (.AN(n_255),
	.B(P[2]),
	.Y(n_257));
   NAND2X2 g133 (.A(n_403),
	.B(n_404),
	.Y(n_255));
   NOR2X4 g10572 (.A(reset),
	.B(FE_DBTN1_load),
	.Y(n_262));
   OAI32X1 g48 (.A0(n_235),
	.A1(reset),
	.A2(n_446),
	.B0(n_358),
	.B1(n_247),
	.Y(n_275));
   AOI21X1 g188 (.A0(n_262),
	.A1(Q[3]),
	.B0(n_277),
	.Y(n_278));
   NOR3X1 g189 (.A(n_276),
	.B(reset),
	.C(load),
	.Y(n_277));
   NAND2BXL g191 (.AN(n_255),
	.B(P[3]),
	.Y(n_276));
   OAI21X1 g154 (.A0(n_307),
	.A1(n_309),
	.B0(FE_DBTN0_reset),
	.Y(n_311));
   NOR2X1 g156 (.A(n_257),
	.B(load),
	.Y(n_307));
   NOR2X1 g155 (.A(n_308),
	.B(FE_DBTN1_load),
	.Y(n_309));
   INVX3 g157 (.A(Q[2]),
	.Y(n_308));
   NAND2X1 g18 (.A(FE_DBTN1_load),
	.B(n_313),
	.Y(n_314));
   NOR2X2 g19 (.A(n_255),
	.B(reset),
	.Y(n_313));
   NAND2X1 g24 (.A(FE_DBTN0_reset),
	.B(n_317),
	.Y(n_318));
   NOR2BX2 g25 (.AN(n_316),
	.B(load),
	.Y(n_317));
   NOR2XL g26 (.A(n_14),
	.B(n_229),
	.Y(n_316));
   NAND4XL g117 (.A(n_322),
	.B(n_323),
	.C(n_329),
	.D(n_328),
	.Y(n_326));
   NAND3X1 g119 (.A(P[5]),
	.B(n_229),
	.C(FE_DBTN0_reset),
	.Y(n_322));
   NAND3X1 g118 (.A(P[5]),
	.B(load),
	.C(FE_DBTN0_reset),
	.Y(n_323));
   NAND2X1 g10588 (.A(n_97),
	.B(n_327),
	.Y(n_328));
   NOR2X8 g10589 (.A(load),
	.B(reset),
	.Y(n_327));
   NAND2X1 g10590 (.A(n_93),
	.B(n_327),
	.Y(n_329));
   NAND3XL g10372__10591 (.A(n_42),
	.B(n_98),
	.C(n_327),
	.Y(n_330));
   NAND2X1 g10448__10592 (.A(M_temp[0]),
	.B(n_327),
	.Y(n_331));
   NAND2X1 g10447__10593 (.A(M_temp[3]),
	.B(n_332),
	.Y(n_333));
   NOR2X8 g546_dup (.A(load),
	.B(reset),
	.Y(n_332));
   NAND2X1 g10446__10594 (.A(M_temp[1]),
	.B(n_332),
	.Y(n_334));
   AOI22X1 g10399__10595 (.A0(n_332),
	.A1(n_44),
	.B0(Q[0]),
	.B1(n_262),
	.Y(n_335));
   NAND2X1 g10445__10596 (.A(M_temp[2]),
	.B(n_332),
	.Y(n_336));
   CLKINVX2 g35 (.A(n_337),
	.Y(n_338));
   NOR3X6 g36 (.A(n_229),
	.B(load),
	.C(reset),
	.Y(n_337));
   INVXL fopt10604 (.A(P[3]),
	.Y(n_352));
   OAI21X1 g10387__10606 (.A0(n_355),
	.A1(n_314),
	.B0(n_335),
	.Y(n_356));
   INVXL g10607 (.A(P[0]),
	.Y(n_355));
   NAND2X1 g10417__10608 (.A(P[0]),
	.B(n_255),
	.Y(n_358));
   AOI22XL g10451__10610 (.A0(n_355),
	.A1(n_235),
	.B0(P[0]),
	.B1(Q_minus_one),
	.Y(n_359));
   NOR3X8 g10633 (.A(n_124),
	.B(reset),
	.C(load),
	.Y(n_388));
   NAND2XL g10364__10634 (.A(n_330),
	.B(n_391),
	.Y(n_392));
   AOI21X1 g10368__10635 (.A0(n_388),
	.A1(n_389),
	.B0(n_390),
	.Y(n_391));
   OAI21XL g10380__10636 (.A0(n_235),
	.A1(n_91),
	.B0(n_92),
	.Y(n_389));
   NOR3BX2 g10637 (.AN(P[6]),
	.B(reset),
	.C(n_446),
	.Y(n_390));
   INVXL fopt10638 (.A(P[2]),
	.Y(n_393));
   CLKINVX2 g10642 (.A(Count[2]),
	.Y(n_403));
   OAI211X1 g10643 (.A0(n_403),
	.A1(n_404),
	.B0(FE_DBTN0_reset),
	.C0(n_405),
	.Y(n_407));
   NOR2X2 g10644 (.A(Count[0]),
	.B(Count[1]),
	.Y(n_404));
   NAND2X4 g10645 (.A(Count[2]),
	.B(load),
	.Y(n_405));
   NOR2X4 g10419__10514_dup10674 (.A(n_229),
	.B(load),
	.Y(n_446));
   NAND2BX1 g2 (.AN(n_200),
	.B(n_9),
	.Y(n_448));
endmodule

